name: GitHub Profile Summary Cards

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 6:15 AM UTC
    - cron: "15 6 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate profile analytics

    steps:
      - name: Check out profile repository
        uses: actions/checkout@v4

      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: msspranavasai
          BRANCH_NAME: main
          UTC_OFFSET: -5
          EXCLUDE: ""
          AUTO_PUSH: true
          THEME: github_dark
          ANIMATION: sequence
          DURATION: 3
          NAME: "Pranava Sai"
